import os
import sys
import json
import time
import operator
from typing import TypedDict, Annotated, List, Dict, Any, Optional, Literal
from pydantic import BaseModel, Field
from dotenv import load_dotenv

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

from langgraph.graph import StateGraph, END, START
from langgraph.prebuilt import ToolNode
from langgraph.graph.message import add_messages
from langchain_groq import ChatGroq
from langchain_core.tools import tool
from langchain_core.messages import AnyMessage, SystemMessage, ToolMessage

load_dotenv()

# =========================================================
# CONFIGURATION
# =========================================================
os.environ["GROQ_API_KEY"] = "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"
MODEL_NAME = "openai/gpt-oss-120b"

# =========================================================
# PYDANTIC MODELS
# =========================================================

class Task(BaseModel):
    id: str = Field(..., description="Unique task ID generated by Python.")
    agent: Literal["WorkspaceAgent", "KnowledgeAgent", "ProductivityAgent"]
    instruction: str
    context_artifacts: List[str] = Field(default_factory=list)
    expected_output: str
    status: str = "pending"

class Artifact(BaseModel):
    id: str
    type: str
    title: str
    description: str
    metadata: Dict[str, Any] = Field(default_factory=dict)
    payload: Any = None

class OrchestratorTask(BaseModel):
    agent: Literal["WorkspaceAgent", "KnowledgeAgent", "ProductivityAgent"]
    instruction: str
    context_artifacts: List[str] = Field(default_factory=list)
    expected_output: str

class OrchestratorDecision(BaseModel):
    finished: bool = Field(..., description="True if the user query is fully resolved.")
    task: Optional[OrchestratorTask] = Field(None, description="The single next task to assign.")
    final_response: Optional[str] = Field(None, description="Final message to user when finished.")

# =========================================================
# STATE
# =========================================================

def merge_dicts(a: dict, b: dict) -> dict:
    c = a.copy()
    c.update(b)
    return c

class GraphState(TypedDict):
    user_query: str
    messages: Annotated[list[AnyMessage], add_messages]
    workspace_messages: Annotated[list[AnyMessage], add_messages]
    knowledge_messages: Annotated[list[AnyMessage], add_messages]
    productivity_messages: Annotated[list[AnyMessage], add_messages]
    current_task: Optional[Task]
    completed_tasks: Annotated[list[Task], operator.add]
    artifacts: Annotated[Dict[str, Artifact], merge_dicts]
    logs: Annotated[list[str], operator.add]
    final_response: Optional[str]
    task_counter: int
    artifact_counter: int
    agent_steps: int  # counts tool loops within the current agent task

MAX_AGENT_STEPS = 3  # force finalize after this many tool loops

# =========================================================
# TOOLS
# =========================================================


@tool
def read_file(path: str) -> str:
    """Read contents of a file from disk."""
    print(f"  [Tool] read_file({path})")

    try:
       
        if not os.path.exists(path):            
            return f"Error: File does not exist -> {path}"
      
        if not os.path.isfile(path):
            return f"Error: Path is not a file -> {path}"

        with open(path, "r", encoding="utf-8") as f:
            content = f.read()

        if not content.strip():
            return f"File is empty -> {path}"
        
        # print(content)
        # print("ritesh")

        return content

    except Exception as e:
        return f"Error reading file: {str(e)}"


@tool
def search_file(name: str) -> str:
    """Search for files matching a name query."""
    print(f"  [Tool] search_file({name})")

    try:
        matches = []

        for root, dirs, files in os.walk("."):
            for file in files:
                if name.lower() in file.lower():
                    full_path = os.path.join(root, file)
                    matches.append(full_path)

        # print(matches)
        if not matches:
            return f"No files found matching '{name}'"

        return "\n".join(matches)

    except Exception as e:
        return f"Error searching file: {str(e)}"


@tool
def create_folder(path: str) -> str:
    """Create a new directory at the given path."""
    print(f"  [Tool] create_folder({path})")

    try:
        os.makedirs(path, exist_ok=True)
        return f"Folder created successfully at: {path}"

    except Exception as e:
        return f"Error creating folder: {str(e)}"


@tool
def write_file(path: str, text: str) -> str:
    """Write text content to a file at the given path."""
    print(f"  [Tool] write_file({path})")

    try:
        parent_dir = os.path.dirname(path)

        if parent_dir:
            os.makedirs(parent_dir, exist_ok=True)

        with open(path, "w", encoding="utf-8") as f:
            f.write(text)

        return f"Written successfully to {path}"

    except Exception as e:
        return f"Error writing file: {str(e)}"

@tool
def summarize(text: str) -> str:
    """Summarize the provided text."""
    print("  [Tool] summarize(...)")
    return (
        "SUMMARY: This project is a hierarchical multi-agent AI assistant prototype "
        "built with LangGraph and Groq. It features an Orchestrator that delegates tasks "
        "to three specialized agents: WorkspaceAgent (files), KnowledgeAgent (research), "
        "and ProductivityAgent (email/calendar). Each agent uses bound tools via ToolNode."
    )

@tool
def write_essay(topic: str) -> str:
    """Write an essay on the given topic."""
    print(f"  [Tool] write_essay({topic})")
    return f"This is a mock essay about: {topic}"

@tool
def answer_question(question: str) -> str:
    """Answer a factual question."""
    print(f"  [Tool] answer_question({question})")
    return f"Mock answer to: {question}"

@tool
def send_email(to: str, subject: str, body: str) -> str:
    """Send an email to the specified recipient using Gmail SMTP if credentials exist, else mock it."""
    from datetime import datetime
    import smtplib
    from email.message import EmailMessage
    
    print(f"  [Tool] send_email(to={to})")
    
    # Read credentials from .env
    sender_email = os.getenv("GMAIL_ADDRESS", "smartdeskgenai@gmail.com")
    app_password = os.getenv("GMAIL_APP_PASSWORD")
    
    if app_password:
        try:
            msg = EmailMessage()
            msg["Subject"] = subject
            msg["From"] = sender_email
            msg["To"] = to
            msg.set_content(body)
            
            with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
                server.login(sender_email, app_password)
                server.send_message(msg)
            return f"Email successfully sent to {to} via SMTP."
        except Exception as e:
            return f"Error sending email via SMTP: {str(e)}"
    else:
        # Fallback to local JSON mock
        try:
            outbox_file = "email_outbox.json"
            emails = []
            if os.path.exists(outbox_file):
                with open(outbox_file, "r") as f:
                    emails = json.load(f)
            
            emails.append({"to": to, "subject": subject, "body": body, "timestamp": datetime.now().isoformat()})
            
            with open(outbox_file, "w") as f:
                json.dump(emails, f, indent=4)
                
            return f"Email mock-queued to {to}. (Set GMAIL_APP_PASSWORD in .env for real sending)"
        except Exception as e:
            return f"Error mock-sending email: {str(e)}"

def get_calendar_service():
    try:
        import os.path
        from google.oauth2.credentials import Credentials
        from google_auth_oauthlib.flow import InstalledAppFlow
        from google.auth.transport.requests import Request
        from googleapiclient.discovery import build
        
        SCOPES = ["https://www.googleapis.com/auth/calendar"]
        creds = None
        
        if os.path.exists("token.json"):
            creds = Credentials.from_authorized_user_file("token.json", SCOPES)
            
        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                creds.refresh(Request())
            elif os.path.exists("credentials.json"):
                flow = InstalledAppFlow.from_client_secrets_file("credentials.json", SCOPES)
                creds = flow.run_local_server(port=0)
                with open("token.json", "w") as token:
                    token.write(creds.to_json())
            else:
                return None # No credentials provided
                
        return build("calendar", "v3", credentials=creds)
    except ImportError:
        pass
    return None

@tool
def calendar_today() -> str:
    """Get today's calendar events."""
    print("  [Tool] calendar_today()")
    try:
        service = get_calendar_service()
        if service:
            import datetime as dt
            now = dt.datetime.utcnow().isoformat() + "Z"
            end_of_day = (dt.datetime.utcnow() + dt.timedelta(days=1)).isoformat() + "Z"
            events_result = service.events().list(
                calendarId="primary", timeMin=now, timeMax=end_of_day, 
                singleEvents=True, orderBy="startTime"
            ).execute()
            events = events_result.get("items", [])
            
            if not events:
                return "No upcoming events found for today (Google Calendar)."
                
            today_events = []
            for e in events:
                start = e["start"].get("dateTime", e["start"].get("date"))
                today_events.append(f"{start} - {e['summary']}")
            return " | ".join(today_events)
            
        # Fallback to local JSON mock
        calendar_file = "calendar.json"
        if not os.path.exists(calendar_file):
            return "No events scheduled for today (Mock)."
            
        with open(calendar_file, "r") as f:
            events = json.load(f)
            
        today_events = [f"{e['date']} - {e['title']}" for e in events]
        if not today_events:
            return "No events scheduled for today (Mock)."
            
        return " | ".join(today_events)
    except Exception as e:
        return f"Error reading calendar: {str(e)}"

@tool
def create_event(title: str, date: str) -> str:
    """Create a calendar event with a title and date."""
    print(f"  [Tool] create_event({title}, {date})")
    try:
        service = get_calendar_service()
        if service:
            if "T" in date:
                time_dict = {"dateTime": date}
            else:
                time_dict = {"date": date}
                
            event = {
                "summary": title,
                "start": time_dict,
                "end": time_dict,
            }
            event_result = service.events().insert(calendarId="primary", body=event).execute()
            return f"Event '{title}' scheduled on {date} (Google Calendar ID: {event_result.get('id')})"
            
        # Fallback to local JSON mock
        calendar_file = "calendar.json"
        events = []
        if os.path.exists(calendar_file):
            with open(calendar_file, "r") as f:
                events = json.load(f)
                
        events.append({"title": title, "date": date})
        
        with open(calendar_file, "w") as f:
            json.dump(events, f, indent=4)
            
        return f"Event '{title}' mock-scheduled on {date}. (Need token.json for real Calendar)"
    except Exception as e:
        return f"Error creating event: {str(e)}"

workspace_tools    = [read_file, search_file, create_folder, write_file]
knowledge_tools    = [summarize, write_essay, answer_question]
productivity_tools = [send_email, calendar_today, create_event]

# =========================================================
# LLM INSTANCES  (one per agent, separate bindings)
# =========================================================

orchestrator_llm  = ChatGroq(model=MODEL_NAME, temperature=0).with_structured_output(OrchestratorDecision)
workspace_llm     = ChatGroq(model=MODEL_NAME, temperature=0).bind_tools(workspace_tools)
knowledge_llm     = ChatGroq(model=MODEL_NAME, temperature=0).bind_tools(knowledge_tools)
productivity_llm  = ChatGroq(model=MODEL_NAME, temperature=0).bind_tools(productivity_tools)

# =========================================================
# TOOL NODES  (one per agent, separate instances)
# =========================================================

workspace_tool_node    = ToolNode(workspace_tools, messages_key="workspace_messages")
knowledge_tool_node    = ToolNode(knowledge_tools, messages_key="knowledge_messages")
productivity_tool_node = ToolNode(productivity_tools, messages_key="productivity_messages")

# =========================================================
# ORCHESTRATOR
# =========================================================

def orchestrator(state: GraphState) -> dict:
    print("\n--- [Orchestrator] Deciding next step ---")

    # Respect Groq's 8000 TPM rate limit
    time.sleep(3)

    completed = [
        {"id": t.id, "agent": t.agent, "status": t.status, "instruction": t.instruction}
        for t in state.get("completed_tasks", [])
    ]
    artifact_summaries = [
        {"id": a.id, "title": a.title, "description": a.description}
        for a in state.get("artifacts", {}).values()
    ]

    prompt = f"""You are the Orchestrator of a hierarchical multi-agent AI system.
You must assign ONE task at a time to the most appropriate agent.

User Query: {state['user_query']}

Completed Tasks (with instructions):
{json.dumps(completed, indent=2)}

Available Artifacts:
{json.dumps(artifact_summaries, indent=2)}

Strict Rules:
1. Assign exactly ONE next task to WorkspaceAgent, KnowledgeAgent, or ProductivityAgent.
2. Look at the completed task instructions carefully. If all tasks required to fulfill the user query are completed, set finished=True NOW.
3. Do NOT repeat a task type that is already completed.
4. Only assign tasks that are directly necessary to answer the user query.
5. Do NOT set finished=True if there are pending actions requested in the user query that have not been performed yet.
6. When setting finished=True, you MUST write a final_response answering the user's query using the content/payload of the completed task artifacts.
7. When you read a file, print its content in final response which u will get in payload. 
"""

    decision: OrchestratorDecision = orchestrator_llm.invoke([SystemMessage(content=prompt)])

    if decision.finished or decision.task is None:
        # decision.task being None means the model thinks we're done (or made an output error)
        final_msg = decision.final_response or "All tasks completed successfully."
        print("  [Orchestrator] All done. Final response ready.")
        return {"final_response": final_msg}

    new_task_counter = state["task_counter"] + 1
    new_task = Task(
        id=f"task_{new_task_counter}",
        agent=decision.task.agent,
        instruction=decision.task.instruction,
        context_artifacts=decision.task.context_artifacts,
        expected_output=decision.task.expected_output,
        status="pending",
    )
    print(f"  [Orchestrator] Assigned {new_task.id} -> {new_task.agent}")
    return {
        "current_task": new_task,
        "task_counter": new_task_counter,
        "agent_steps": 0,
        "logs": [f"Orchestrator -> {new_task.agent}: {new_task.id}"],
    }


def orchestrator_route(state: GraphState) -> str:
    if state.get("final_response"):
        return END
    task = state.get("current_task")
    if task is None:
        return END
    return task.agent


# =========================================================
# WORKSPACE AGENT
# =========================================================

def workspace_agent(state: GraphState) -> dict:
    task = state["current_task"]
    print(f"\n--- [WorkspaceAgent] Executing {task.id} ---")

    context = {
        aid: state["artifacts"][aid].payload
        for aid in task.context_artifacts
        if aid in state["artifacts"]
    }

    sys_prompt = f"""You are WorkspaceAgent. You handle file system operations.
Task: {task.instruction}
Expected Output: {task.expected_output}
Context: {json.dumps(context)}

Use the available tools to complete the task. You may call multiple tools if needed."""

    # On first call (agent_steps==0): fresh start, no prior history needed.
    # On subsequent calls: include history so LLM sees its own tool results.
    if state["agent_steps"] == 0:
        messages = [SystemMessage(content=sys_prompt)]
    else:
        messages = [SystemMessage(content=sys_prompt)] + state["workspace_messages"]

    time.sleep(2)  # respect TPM rate limit
    response = workspace_llm.invoke(messages)

    if response.tool_calls:
        print(f"  [WorkspaceAgent] Tool calls: {[tc['name'] for tc in response.tool_calls]}")
    else:
        print("  [WorkspaceAgent] Done — no more tool calls.")

    return {"workspace_messages": [response], "agent_steps": state["agent_steps"] + 1}


def workspace_route(state: GraphState) -> str:
    # Safety guard: force finalize if too many tool loops
    if state["agent_steps"] >= MAX_AGENT_STEPS:
        print("  [WorkspaceAgent] Max steps reached, forcing finalize.")
        return "WorkspaceFinalizer"
    last_msg = state["workspace_messages"][-1]
    if hasattr(last_msg, "tool_calls") and last_msg.tool_calls:
        return "WorkspaceToolNode"
    return "WorkspaceFinalizer"


def workspace_finalizer(state: GraphState) -> dict:
    print("  [WorkspaceAgent] Finalizing task.")
    last_msg = state["workspace_messages"][-1]

    if isinstance(last_msg, ToolMessage):
        payload   = last_msg.content
        tool_name = last_msg.name
    else:
        payload   = last_msg.content
        tool_name = "direct_response"

    task = state["current_task"]
    new_art_counter = state["artifact_counter"] + 1
    artifact_id = f"art_{new_art_counter}"

    artifact = Artifact(
        id=artifact_id,
        type="workspace_output",
        title=f"Output of {tool_name}",
        description=f"Produced by WorkspaceAgent for {task.id}",
        payload=payload,
    )

    task.status = "completed"
    print(f"  [WorkspaceAgent] Created artifact {artifact_id}.")

    return {
        "artifacts": {artifact_id: artifact},
        "completed_tasks": [task],
        "current_task": None,
        "artifact_counter": new_art_counter,
        "agent_steps": 0,
        "logs": [f"WorkspaceAgent completed {task.id} -> {artifact_id}"],
    }


# =========================================================
# KNOWLEDGE AGENT
# =========================================================

def knowledge_agent(state: GraphState) -> dict:
    task = state["current_task"]
    print(f"\n--- [KnowledgeAgent] Executing {task.id} ---")

    context = {
        aid: state["artifacts"][aid].payload
        for aid in task.context_artifacts
        if aid in state["artifacts"]
    }

    sys_prompt = f"""You are KnowledgeAgent. You handle summarization, research, and writing tasks.
Task: {task.instruction}
Expected Output: {task.expected_output}
Context: {json.dumps(context)}

Use the available tools to complete the task. You may call multiple tools if needed."""

    if state["agent_steps"] == 0:
        messages = [SystemMessage(content=sys_prompt)]
    else:
        messages = [SystemMessage(content=sys_prompt)] + state["knowledge_messages"]

    time.sleep(2)  # respect TPM rate limit
    response = knowledge_llm.invoke(messages)

    if response.tool_calls:
        print(f"  [KnowledgeAgent] Tool calls: {[tc['name'] for tc in response.tool_calls]}")
    else:
        print("  [KnowledgeAgent] Done — no more tool calls.")

    return {"knowledge_messages": [response], "agent_steps": state["agent_steps"] + 1}


def knowledge_route(state: GraphState) -> str:
    # Safety guard: force finalize if too many tool loops
    if state["agent_steps"] >= MAX_AGENT_STEPS:
        print("  [KnowledgeAgent] Max steps reached, forcing finalize.")
        return "KnowledgeFinalizer"
    last_msg = state["knowledge_messages"][-1]
    if hasattr(last_msg, "tool_calls") and last_msg.tool_calls:
        return "KnowledgeToolNode"
    return "KnowledgeFinalizer"


def knowledge_finalizer(state: GraphState) -> dict:
    print("  [KnowledgeAgent] Finalizing task.")
    last_msg = state["knowledge_messages"][-1]

    if isinstance(last_msg, ToolMessage):
        payload   = last_msg.content
        tool_name = last_msg.name
    else:
        payload   = last_msg.content
        tool_name = "direct_response"

    task = state["current_task"]
    new_art_counter = state["artifact_counter"] + 1
    artifact_id = f"art_{new_art_counter}"

    artifact = Artifact(
        id=artifact_id,
        type="knowledge_output",
        title=f"Output of {tool_name}",
        description=f"Produced by KnowledgeAgent for {task.id}",
        payload=payload,
    )

    task.status = "completed"
    print(f"  [KnowledgeAgent] Created artifact {artifact_id}.")

    return {
        "artifacts": {artifact_id: artifact},
        "completed_tasks": [task],
        "current_task": None,
        "artifact_counter": new_art_counter,
        "agent_steps": 0,
        "logs": [f"KnowledgeAgent completed {task.id} -> {artifact_id}"],
    }


# =========================================================
# PRODUCTIVITY AGENT
# =========================================================

def productivity_agent(state: GraphState) -> dict:
    task = state["current_task"]
    print(f"\n--- [ProductivityAgent] Executing {task.id} ---")

    context = {
        aid: state["artifacts"][aid].payload
        for aid in task.context_artifacts
        if aid in state["artifacts"]
    }

    sys_prompt = f"""You are ProductivityAgent. You handle emails, calendars, and scheduling.
Task: {task.instruction}
Expected Output: {task.expected_output}
Context: {json.dumps(context)}

Use the available tools to complete the task. You may call multiple tools if needed."""

    if state["agent_steps"] == 0:
        messages = [SystemMessage(content=sys_prompt)]
    else:
        messages = [SystemMessage(content=sys_prompt)] + state["productivity_messages"]

    time.sleep(2)  # respect TPM rate limit
    response = productivity_llm.invoke(messages)

    if response.tool_calls:
        print(f"  [ProductivityAgent] Tool calls: {[tc['name'] for tc in response.tool_calls]}")
    else:
        print("  [ProductivityAgent] Done — no more tool calls.")

    return {"productivity_messages": [response], "agent_steps": state["agent_steps"] + 1}


def productivity_route(state: GraphState) -> str:
    # Safety guard: force finalize if too many tool loops
    if state["agent_steps"] >= MAX_AGENT_STEPS:
        print("  [ProductivityAgent] Max steps reached, forcing finalize.")
        return "ProductivityFinalizer"
    last_msg = state["productivity_messages"][-1]
    if hasattr(last_msg, "tool_calls") and last_msg.tool_calls:
        return "ProductivityToolNode"
    return "ProductivityFinalizer"


def productivity_finalizer(state: GraphState) -> dict:
    print("  [ProductivityAgent] Finalizing task.")
    last_msg = state["productivity_messages"][-1]

    if isinstance(last_msg, ToolMessage):
        payload   = last_msg.content
        tool_name = last_msg.name
    else:
        payload   = last_msg.content
        tool_name = "direct_response"

    task = state["current_task"]
    new_art_counter = state["artifact_counter"] + 1
    artifact_id = f"art_{new_art_counter}"

    artifact = Artifact(
        id=artifact_id,
        type="productivity_output",
        title=f"Output of {tool_name}",
        description=f"Produced by ProductivityAgent for {task.id}",
        payload=payload,
    )

    task.status = "completed"
    print(f"  [ProductivityAgent] Created artifact {artifact_id}.")

    return {
        "artifacts": {artifact_id: artifact},
        "completed_tasks": [task],
        "current_task": None,
        "artifact_counter": new_art_counter,
        "agent_steps": 0,
        "logs": [f"ProductivityAgent completed {task.id} -> {artifact_id}"],
    }


# =========================================================
# BUILD GRAPH
# =========================================================

def build_graph():
    builder = StateGraph(GraphState)

    # ── Nodes ────────────────────────────────────────────
    builder.add_node("Orchestrator",        orchestrator)

    builder.add_node("WorkspaceAgent",      workspace_agent)
    builder.add_node("WorkspaceToolNode",   workspace_tool_node)
    builder.add_node("WorkspaceFinalizer",  workspace_finalizer)

    builder.add_node("KnowledgeAgent",      knowledge_agent)
    builder.add_node("KnowledgeToolNode",   knowledge_tool_node)
    builder.add_node("KnowledgeFinalizer",  knowledge_finalizer)

    builder.add_node("ProductivityAgent",      productivity_agent)
    builder.add_node("ProductivityToolNode",   productivity_tool_node)
    builder.add_node("ProductivityFinalizer",  productivity_finalizer)

    # ── Entry ─────────────────────────────────────────────
    builder.add_edge(START, "Orchestrator")

    # ── Orchestrator routes to one agent (or END) ─────────
    builder.add_conditional_edges("Orchestrator", orchestrator_route)

    # ── WorkspaceAgent mini-loop ──────────────────────────
    builder.add_conditional_edges("WorkspaceAgent",   workspace_route)
    builder.add_edge("WorkspaceToolNode",  "WorkspaceAgent")   # loop back for more calls
    builder.add_edge("WorkspaceFinalizer", "Orchestrator")

    # ── KnowledgeAgent mini-loop ──────────────────────────
    builder.add_conditional_edges("KnowledgeAgent",   knowledge_route)
    builder.add_edge("KnowledgeToolNode",  "KnowledgeAgent")   # loop back for more calls
    builder.add_edge("KnowledgeFinalizer", "Orchestrator")

    # ── ProductivityAgent mini-loop ───────────────────────
    builder.add_conditional_edges("ProductivityAgent",   productivity_route)
    builder.add_edge("ProductivityToolNode",  "ProductivityAgent")  # loop back for more calls
    builder.add_edge("ProductivityFinalizer", "Orchestrator")

    return builder.compile()


# =========================================================
# ENTRY POINT
# =========================================================

if __name__ == "__main__":
    graph = build_graph()

    initial_state: GraphState = {
#         "user_query": "search the poem.txt and summarize what it contains. " ,
        "user_query": "Check my calendar for today. Then send an email to chaitanyashinde545@gmail.com summarizing my events today." ,
        "messages": [],
        "workspace_messages": [],
        "knowledge_messages": [],
        "productivity_messages": [],
        "current_task": None,
        "completed_tasks": [],
        "artifacts": {},
        "logs": [],
        "final_response": None,
        "task_counter": 0,
        "artifact_counter": 0,
        "agent_steps": 0,
    }

    print("=========================================================")
    print("  MULTI-AGENT LANGGRAPH — EXPLICIT NODES & TOOL LOOPS")
    print("=========================================================")

    final_state = graph.invoke(initial_state, config={"recursion_limit": 25})

    print("\n=========================================================")
    print("  GRAPH FINISHED")
    print(f"  Final Response  : {final_state.get('final_response')}")
    print(f"  Tasks Completed : {len(final_state.get('completed_tasks', []))}")
    print(f"  Artifacts       : {len(final_state.get('artifacts', {}))}")
    print("=========================================================")
    
    # print(search_file.invoke({"name": "README"}))
    # print(create_folder.invoke({"path": "./demo"}))
    # print(write_file.invoke({"path": "./demo/test.txt", "text": "hello"}))
    # print(read_file.invoke({"path": "./demo/test.txt"}))
    
#    print(search_file.invoke({"name": "test.txt"})) 
#    print( read_file.invoke({"path":"./test.txt"}))
