import json
import operator
import os
import sys
import time
import requests
from typing import Annotated, Any, Dict, List, Literal, Optional, TypedDict

from dotenv import load_dotenv
from pydantic import BaseModel, Field

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

from langchain_core.messages import AnyMessage, SystemMessage, ToolMessage
from langchain_core.tools import tool
from langchain_groq import ChatGroq
from langgraph.graph import END, START, StateGraph
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode

load_dotenv()

# =========================================================
# CONFIGURATION
# =========================================================
# GROQ_API_KEY is loaded from .env
MODEL_NAME = "openai/gpt-oss-120b"

# =========================================================
# PYDANTIC MODELS
# =========================================================


class Task(BaseModel):
    id: str = Field(..., description="Unique task ID generated by Python.")
    agent: Literal["WorkspaceAgent", "KnowledgeAgent", "ProductivityAgent"]
    instruction: str
    context_artifacts: List[str] = Field(default_factory=list)
    expected_output: str
    status: str = "pending"


class Artifact(BaseModel):
    id: str
    type: str
    title: str
    description: str
    metadata: Dict[str, Any] = Field(default_factory=dict)
    payload: Any = None


class OrchestratorTask(BaseModel):
    agent: Literal["WorkspaceAgent", "KnowledgeAgent", "ProductivityAgent"]
    instruction: str
    context_artifacts: List[str] = Field(default_factory=list)
    expected_output: str


class OrchestratorDecision(BaseModel):
    finished: bool = Field(..., description="True if the user query is fully resolved.")
    task: Optional[OrchestratorTask] = Field(
        None, description="The single next task to assign."
    )
    final_response: Optional[str] = Field(
        None, description="Final message to user when finished."
    )


# =========================================================
# STATE
# =========================================================


def merge_dicts(a: dict, b: dict) -> dict:
    c = a.copy()
    c.update(b)
    return c


class GraphState(TypedDict):
    user_query: str
    messages: Annotated[list[AnyMessage], add_messages]
    workspace_messages: Annotated[list[AnyMessage], add_messages]
    knowledge_messages: Annotated[list[AnyMessage], add_messages]
    productivity_messages: Annotated[list[AnyMessage], add_messages]
    current_task: Optional[Task]
    completed_tasks: Annotated[list[Task], operator.add]
    artifacts: Annotated[Dict[str, Artifact], merge_dicts]
    logs: Annotated[list[str], operator.add]
    final_response: Optional[str]
    task_counter: int
    artifact_counter: int
    agent_steps: int  # counts tool loops within the current agent task


MAX_AGENT_STEPS = 3  # force finalize after this many tool loops

# =========================================================
# TOOLS
# =========================================================


@tool
def read_file(path: str) -> str:
    """Read contents of a file from disk."""
    print(f"  [Tool] read_file({path})")

    try:
        if not os.path.exists(path):
            return f"Error: File does not exist -> {path}"

        if not os.path.isfile(path):
            return f"Error: Path is not a file -> {path}"

        with open(path, "r", encoding="utf-8") as f:
            content = f.read()

        if not content.strip():
            return f"File is empty -> {path}"

        # print(content)
        # print("ritesh")

        return content

    except Exception as e:
        return f"Error reading file: {str(e)}"


@tool
def search_file(name: str) -> str:
    """Search for files matching a name query."""
    print(f"  [Tool] search_file({name})")

    try:
        matches = []

        for root, dirs, files in os.walk("."):
            for file in files:
                if name.lower() in file.lower():
                    full_path = os.path.join(root, file)
                    matches.append(full_path)

        # print(matches)
        if not matches:
            return f"No files found matching '{name}'"

        return "\n".join(matches)

    except Exception as e:
        return f"Error searching file: {str(e)}"


@tool
def create_folder(path: str) -> str:
    """Create a new directory at the given path."""
    print(f"  [Tool] create_folder({path})")

    try:
        os.makedirs(path, exist_ok=True)
        return f"Folder created successfully at: {path}"

    except Exception as e:
        return f"Error creating folder: {str(e)}"


@tool
def write_file(path: str, text: str) -> str:
    """Write text content to a file at the given path."""
    print(f"  [Tool] write_file({path})")

    try:
        parent_dir = os.path.dirname(path)

        if parent_dir:
            os.makedirs(parent_dir, exist_ok=True)

        with open(path, "w", encoding="utf-8") as f:
            f.write(text)

        return f"Written successfully to {path}"

    except Exception as e:
        return f"Error writing file: {str(e)}"


@tool
def summarize(text: str) -> str:
    """Summarize the provided text."""
    print("  [Tool] summarize(...)")
    return (
        "SUMMARY: This project is a hierarchical multi-agent AI assistant prototype "
        "built with LangGraph and Groq. It features an Orchestrator that delegates tasks "
        "to three specialized agents: WorkspaceAgent (files), KnowledgeAgent (research), "
        "and ProductivityAgent (email/calendar). Each agent uses bound tools via ToolNode."
    )


def get_embeddings():
    try:
        from langchain_huggingface import HuggingFaceEmbeddings
        return HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
    except ImportError:
        from langchain_core.embeddings import FakeEmbeddings
        return FakeEmbeddings(size=384)

@tool
def refresh_knowledge_base() -> str:
    """Scan the knowledge folder and index any new or modified files."""
    print("  [Tool] refresh_knowledge_base()")
    KNOWLEDGE_DIR = "KnowledgeBase"
    CHROMA_DB_DIR = "chroma_db"
    INDEX_METADATA_FILE = "index_metadata.json"
    
    if not os.path.exists(KNOWLEDGE_DIR):
        os.makedirs(KNOWLEDGE_DIR, exist_ok=True)
        return f"Created {KNOWLEDGE_DIR}. Please add files and run again."
        
    try:
        from langchain_community.document_loaders import PyPDFLoader, TextLoader, Docx2txtLoader
        from langchain_text_splitters import RecursiveCharacterTextSplitter
        from langchain_chroma import Chroma
    except ImportError as e:
        return f"Import Error: {str(e)}. Make sure required packages are installed."

    metadata = {}
    if os.path.exists(INDEX_METADATA_FILE):
        try:
            with open(INDEX_METADATA_FILE, "r") as f:
                metadata = json.load(f)
        except Exception:
            pass

    new_or_modified_files = []
    
    for root, _, files in os.walk(KNOWLEDGE_DIR):
        for file in files:
            file_path = os.path.join(root, file)
            mtime = os.path.getmtime(file_path)
            
            if file not in metadata or metadata[file].get("last_modified") != mtime:
                new_or_modified_files.append((file, file_path, mtime))

    if not new_or_modified_files:
        return "Knowledge base is up to date. No new or modified files found."

    docs_to_index = []
    for file, file_path, mtime in new_or_modified_files:
        try:
            if file.lower().endswith(".pdf"):
                loader = PyPDFLoader(file_path)
            elif file.lower().endswith(".md") or file.lower().endswith(".txt"):
                loader = TextLoader(file_path)
            elif file.lower().endswith(".docx"):
                try:
                    loader = Docx2txtLoader(file_path)
                except ImportError:
                    continue
            else:
                continue
                
            docs = loader.load()
            docs_to_index.extend(docs)
            metadata[file] = {"last_modified": mtime}
        except Exception as e:
            print(f"Error loading {file}: {e}")

    if not docs_to_index:
        return "No supported files were successfully read."

    text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=100)
    splits = text_splitter.split_documents(docs_to_index)
    
    embeddings = get_embeddings()
    Chroma.from_documents(documents=splits, embedding=embeddings, persist_directory=CHROMA_DB_DIR)
    
    with open(INDEX_METADATA_FILE, "w") as f:
        json.dump(metadata, f, indent=4)
        
    return f"Successfully indexed {len(new_or_modified_files)} new/modified files."

@tool
def rag_search(query: str) -> str:
    """Search the knowledge base."""
    print(f"  [Tool] rag_search({query})")
    CHROMA_DB_DIR = "chroma_db"
    if not os.path.exists(CHROMA_DB_DIR):
        return "Knowledge base is empty. Please run refresh_knowledge_base()."
        
    try:
        from langchain_chroma import Chroma
    except ImportError as e:
        return f"Import Error: {str(e)}."
        
    embeddings = get_embeddings()
    vectorstore = Chroma(persist_directory=CHROMA_DB_DIR, embedding_function=embeddings)
    
    results = vectorstore.similarity_search(query, k=5)
    
    if not results:
        return "No relevant information found in the knowledge base."
        
    formatted_results = []
    for i, res in enumerate(results):
        source = res.metadata.get("source", "Unknown")
        formatted_results.append(f"--- Chunk {i+1} from {source} ---\n{res.page_content}")
        
    return "\n\n".join(formatted_results)


@tool
def send_email(to: str, subject: str, body: str) -> str:
    """Send an email to the specified recipient using Gmail SMTP if credentials exist, else mock it."""
    import smtplib
    from datetime import datetime
    from email.message import EmailMessage

    print(f"  [Tool] send_email(to={to})")

    # Read credentials from .env
    sender_email = os.getenv("GMAIL_ADDRESS", "smartdeskgenai@gmail.com")
    app_password = os.getenv("GMAIL_APP_PASSWORD")

    if app_password:
        try:
            msg = EmailMessage()
            msg["Subject"] = subject
            msg["From"] = sender_email
            msg["To"] = to
            msg.set_content(body)

            with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
                server.login(sender_email, app_password)
                server.send_message(msg)
            return f"Email successfully sent to {to} via SMTP."
        except Exception as e:
            return f"Error sending email via SMTP: {str(e)}"
    else:
        # Fallback to local JSON mock
        try:
            outbox_file = "email_outbox.json"
            emails = []
            if os.path.exists(outbox_file):
                with open(outbox_file, "r") as f:
                    emails = json.load(f)

            emails.append(
                {
                    "to": to,
                    "subject": subject,
                    "body": body,
                    "timestamp": datetime.now().isoformat(),
                }
            )

            with open(outbox_file, "w") as f:
                json.dump(emails, f, indent=4)

            return f"Email mock-queued to {to}. (Set GMAIL_APP_PASSWORD in .env for real sending)"
        except Exception as e:
            return f"Error mock-sending email: {str(e)}"


def get_google_credentials():
    import os.path
    import json

    from google.auth.transport.requests import Request
    from google.oauth2.credentials import Credentials
    from google_auth_oauthlib.flow import InstalledAppFlow
    from google.auth.exceptions import RefreshError

    SCOPES = [
        "https://www.googleapis.com/auth/calendar",
        "https://www.googleapis.com/auth/tasks",
        "https://www.googleapis.com/auth/drive.file",
        "https://www.googleapis.com/auth/documents"
    ]
    creds = None
    
    # Check scopes manually before loading
    if os.path.exists("token.json"):
        try:
            with open("token.json", "r") as f:
                token_data = json.load(f)
            token_scopes = token_data.get("scopes", [])
            # If any required scope is missing, we must re-auth
            if not all(s in token_scopes for s in SCOPES):
                print("  [Auth] Scopes updated. Requires re-authentication. Falling back to mock for now.")
                return None
            creds = Credentials.from_authorized_user_file("token.json", SCOPES)
        except Exception:
            pass

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            try:
                creds.refresh(Request())
            except RefreshError:
                return None
        elif os.path.exists("credentials.json"):
            # Don't trigger browser if in automated test
            if os.environ.get("HEADLESS_TEST") == "1":
                return None
            flow = InstalledAppFlow.from_client_secrets_file(
                "credentials.json", SCOPES
            )
            creds = flow.run_local_server(port=0)
            with open("token.json", "w") as token:
                token.write(creds.to_json())
        else:
            return None  # No credentials provided

    return creds


def get_google_service(name, version):
    try:
        from googleapiclient.discovery import build
        creds = get_google_credentials()
        if creds:
            return build(name, version, credentials=creds)
    except ImportError:
        pass
    return None


@tool
def calendar_today() -> str:
    """Get today's calendar events."""
    print("  [Tool] calendar_today()")
    try:
        service = get_google_service("calendar", "v3")
        if service:
            import datetime as dt

            now = dt.datetime.utcnow().isoformat() + "Z"
            end_of_day = (dt.datetime.utcnow() + dt.timedelta(days=1)).isoformat() + "Z"
            events_result = (
                service.events()
                .list(
                    calendarId="primary",
                    timeMin=now,
                    timeMax=end_of_day,
                    singleEvents=True,
                    orderBy="startTime",
                )
                .execute()
            )
            events = events_result.get("items", [])

            if not events:
                return "No upcoming events found for today (Google Calendar)."
            # print("chaitanya",events)
            today_events = []
            for e in events:
                start = e["start"].get("dateTime", e["start"].get("date"))
                today_events.append(f"{start} - {e['summary']} - {e['description']}")
            print(today_events)
            return " | ".join(today_events)

        # Fallback to local JSON mock
        calendar_file = "calendar.json"
        if not os.path.exists(calendar_file):
            return "No events scheduled for today (Mock)."

        with open(calendar_file, "r") as f:
            events = json.load(f)

        today_events = [f"{e['date']} - {e['title']}" for e in events]
        if not today_events:
            return "No events scheduled for today (Mock)."

        return " | ".join(today_events)
    except Exception as e:
        return f"Error reading calendar: {str(e)}"


@tool
def create_event(title: str, date: str) -> str:
    """Create a calendar event with a title and date."""
    print(f"  [Tool] create_event({title}, {date})")
    try:
        service = get_google_service("calendar", "v3")
        if service:
            if "T" in date:
                time_dict = {"dateTime": date}
            else:
                time_dict = {"date": date}

            event = {
                "summary": title,
                "start": time_dict,
                "end": time_dict,
            }
            event_result = (
                service.events().insert(calendarId="primary", body=event).execute()
            )
            return f"Event '{title}' scheduled on {date} (Google Calendar ID: {event_result.get('id')})"

        # Fallback to local JSON mock
        calendar_file = "calendar.json"
        events = []
        if os.path.exists(calendar_file):
            with open(calendar_file, "r") as f:
                events = json.load(f)

        events.append({"title": title, "date": date})

        with open(calendar_file, "w") as f:
            json.dump(events, f, indent=4)

        return f"Event '{title}' mock-scheduled on {date}. (Need token.json for real Calendar)"
    except Exception as e:
        return f"Error creating event: {str(e)}"


@tool
def create_task(title: str, due_date: str = None) -> str:
    """Create a task in Google Tasks. due_date should be RFC3339 format if provided."""
    print(f"  [Tool] create_task({title}, {due_date})")
    try:
        service = get_google_service("tasks", "v1")
        if service:
            task = {"title": title}
            if due_date:
                task["due"] = due_date
            result = service.tasks().insert(tasklist="@default", body=task).execute()
            return f"Task '{title}' created (Google Tasks ID: {result.get('id')})"
        
        # Mock fallback
        tasks_file = "tasks.json"
        tasks = []
        if os.path.exists(tasks_file):
            with open(tasks_file, "r") as f:
                tasks = json.load(f)
        tasks.append({"title": title, "due": due_date})
        with open(tasks_file, "w") as f:
            json.dump(tasks, f, indent=4)
        return f"Task '{title}' mock-created. (Need token.json for real Tasks)"
    except Exception as e:
        return f"Error creating task: {str(e)}"


@tool
def list_tasks() -> str:
    """List pending tasks from Google Tasks."""
    print("  [Tool] list_tasks()")
    try:
        service = get_google_service("tasks", "v1")
        if service:
            results = service.tasks().list(tasklist="@default", showCompleted=False).execute()
            items = results.get("items", [])
            if not items:
                return "No pending tasks found."
            return " | ".join([f"{t.get('title')} (Due: {t.get('due', 'None')})" for t in items])

        # Mock fallback
        tasks_file = "tasks.json"
        if not os.path.exists(tasks_file):
            return "No tasks found (Mock)."
        with open(tasks_file, "r") as f:
            tasks = json.load(f)
        return " | ".join([f"{t['title']} (Due: {t.get('due', 'None')})" for t in tasks])
    except Exception as e:
        return f"Error reading tasks: {str(e)}"


@tool
def upload_to_drive(file_path: str, mime_type: str = None) -> str:
    """Upload a local file to Google Drive."""
    print(f"  [Tool] upload_to_drive({file_path})")
    try:
        if not os.path.exists(file_path):
            return f"Error: File does not exist -> {file_path}"
        
        service = get_google_service("drive", "v3")
        if service:
            from googleapiclient.http import MediaFileUpload
            file_name = os.path.basename(file_path)
            file_metadata = {"name": file_name}
            media = MediaFileUpload(file_path, mimetype=mime_type)
            result = service.files().create(body=file_metadata, media_body=media, fields="id").execute()
            return f"File '{file_name}' uploaded to Drive (ID: {result.get('id')})"
        
        return f"Mock: File '{file_path}' ready to be uploaded. (Need token.json for real Drive)"
    except Exception as e:
        return f"Error uploading to Drive: {str(e)}"


@tool
def search_drive(query: str) -> str:
    """Search for files in Google Drive using a search query (e.g., "name contains 'Project'")."""
    print(f"  [Tool] search_drive({query})")
    try:
        service = get_google_service("drive", "v3")
        if service:
            results = service.files().list(q=query, spaces="drive", fields="files(id, name)").execute()
            items = results.get("files", [])
            if not items:
                return "No files found in Drive."
            return " | ".join([f"{f['name']} (ID: {f['id']})" for f in items])
        
        return "Mock: Searched Drive. (Need token.json for real Drive)"
    except Exception as e:
        return f"Error searching Drive: {str(e)}"


@tool
def send_telegram_message(text: str) -> str:
    """Send a message via Telegram bot."""
    print("  [Tool] send_telegram_message(...)")
    token = os.getenv("TELEGRAM_BOT_TOKEN")
    chat_id = os.getenv("TELEGRAM_CHAT_ID")
    
    if token and chat_id:
        try:
            url = f"https://api.telegram.org/bot{token}/sendMessage"
            payload = {"chat_id": chat_id, "text": text}
            response = requests.post(url, json=payload)
            if response.status_code == 200:
                return "Telegram message sent successfully."
            else:
                return f"Error sending Telegram message: {response.text}"
        except Exception as e:
            return f"Error: {str(e)}"
    
    # Mock fallback
    try:
        outbox_file = "telegram_outbox.json"
        messages = []
        if os.path.exists(outbox_file):
            with open(outbox_file, "r") as f:
                messages = json.load(f)
        from datetime import datetime
        messages.append({"text": text, "timestamp": datetime.now().isoformat()})
        with open(outbox_file, "w") as f:
            json.dump(messages, f, indent=4)
        return "Message mock-queued to Telegram. (Set TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID in .env for real sending)"
    except Exception as e:
        return f"Error mock-sending Telegram message: {str(e)}"

@tool
def create_doc(title: str, text: str = "") -> str:
    """Create a new Google Doc and optionally insert text."""
    print(f"  [Tool] create_doc({title})")
    try:
        service = get_google_service("docs", "v1")
        if service:
            doc = service.documents().create(body={"title": title}).execute()
            doc_id = doc.get("documentId")
            
            if text:
                requests_list = [
                    {
                        "insertText": {
                            "location": {"index": 1},
                            "text": text
                        }
                    }
                ]
                service.documents().batchUpdate(documentId=doc_id, body={"requests": requests_list}).execute()
            
            return f"Google Doc '{title}' created (ID: {doc_id})"
            
        # Mock fallback
        docs_file = "docs_mock.json"
        docs = {}
        if os.path.exists(docs_file):
            with open(docs_file, "r") as f:
                docs = json.load(f)
        doc_id = f"mock_{len(docs)+1}"
        docs[doc_id] = {"title": title, "text": text}
        with open(docs_file, "w") as f:
            json.dump(docs, f, indent=4)
        return f"Google Doc '{title}' mock-created (ID: {doc_id}). (Need token.json for real Docs)"
    except Exception as e:
        return f"Error creating doc: {str(e)}"

@tool
def read_doc(doc_id: str) -> str:
    """Read the text content of a Google Doc."""
    print(f"  [Tool] read_doc({doc_id})")
    try:
        service = get_google_service("docs", "v1")
        if service:
            doc = service.documents().get(documentId=doc_id).execute()
            content = ""
            for element in doc.get("body").get("content"):
                if "paragraph" in element:
                    for p_element in element.get("paragraph").get("elements"):
                        if "textRun" in p_element:
                            content += p_element.get("textRun").get("content")
            return content
            
        # Mock fallback
        docs_file = "docs_mock.json"
        if os.path.exists(docs_file):
            with open(docs_file, "r") as f:
                docs = json.load(f)
            if doc_id in docs:
                return docs[doc_id].get("text", "")
        return f"Error: Mock Doc '{doc_id}' not found."
    except Exception as e:
        return f"Error reading doc: {str(e)}"

@tool
def append_to_doc(doc_id: str, text: str) -> str:
    """Append text to the end of an existing Google Doc."""
    print(f"  [Tool] append_to_doc({doc_id})")
    try:
        service = get_google_service("docs", "v1")
        if service:
            doc = service.documents().get(documentId=doc_id).execute()
            end_index = 1
            content_elements = doc.get("body", {}).get("content", [])
            if content_elements:
                last_element = content_elements[-1]
                end_index = last_element.get("endIndex", 1) - 1
                
            requests_list = [
                {
                    "insertText": {
                        "location": {"index": end_index},
                        "text": "\\n" + text
                    }
                }
            ]
            service.documents().batchUpdate(documentId=doc_id, body={"requests": requests_list}).execute()
            return f"Appended text to Google Doc (ID: {doc_id})"
            
        # Mock fallback
        docs_file = "docs_mock.json"
        if os.path.exists(docs_file):
            with open(docs_file, "r") as f:
                docs = json.load(f)
            if doc_id in docs:
                docs[doc_id]["text"] += "\\n" + text
                with open(docs_file, "w") as f:
                    json.dump(docs, f, indent=4)
                return f"Appended text to Mock Doc (ID: {doc_id})."
        return f"Error: Mock Doc '{doc_id}' not found."
    except Exception as e:
        return f"Error appending to doc: {str(e)}"

@tool
def reschedule_event(event_id: str, new_date: str) -> str:
    """Reschedule an existing Google Calendar event. new_date should be RFC3339 format or YYYY-MM-DD."""
    print(f"  [Tool] reschedule_event({event_id}, {new_date})")
    try:
        service = get_google_service("calendar", "v3")
        if service:
            event = service.events().get(calendarId='primary', eventId=event_id).execute()
            if "T" in new_date:
                time_dict = {"dateTime": new_date}
            else:
                time_dict = {"date": new_date}
            event["start"] = time_dict
            event["end"] = time_dict
            updated_event = service.events().update(calendarId='primary', eventId=event_id, body=event).execute()
            return f"Event rescheduled to {new_date}."
            
        return f"Mock: Event '{event_id}' rescheduled to {new_date}."
    except Exception as e:
        return f"Error rescheduling event: {str(e)}"

@tool
def delete_event(event_id: str) -> str:
    """Delete a Google Calendar event by ID."""
    print(f"  [Tool] delete_event({event_id})")
    try:
        service = get_google_service("calendar", "v3")
        if service:
            service.events().delete(calendarId='primary', eventId=event_id).execute()
            return f"Event '{event_id}' deleted."
            
        return f"Mock: Event '{event_id}' deleted."
    except Exception as e:
        return f"Error deleting event: {str(e)}"

@tool
def share_drive_file(file_id: str, email: str, role: str = "reader") -> str:
    """Share a Google Drive file with a specific email. role can be 'reader', 'commenter', or 'writer'."""
    print(f"  [Tool] share_drive_file({file_id}, {email})")
    try:
        service = get_google_service("drive", "v3")
        if service:
            user_permission = {
                'type': 'user',
                'role': role,
                'emailAddress': email
            }
            service.permissions().create(
                fileId=file_id,
                body=user_permission,
                fields='id',
            ).execute()
            return f"File '{file_id}' shared with {email} as {role}."
            
        return f"Mock: File '{file_id}' shared with {email} as {role}."
    except Exception as e:
        return f"Error sharing file: {str(e)}"

@tool
def lookup_contact(name: str) -> str:
    """Lookup an email address for a given name from the contact book."""
    print(f"  [Tool] lookup_contact({name})")
    import os, json
    contacts_file = "contacts.json"
    if not os.path.exists(contacts_file):
        # Create a dummy contact book if it doesn't exist
        dummy_contacts = {
            "sarah": "sarah.smith@example.com",
            "engineering team": "eng-team@example.com",
            "manager": "boss@example.com"
        }
        with open(contacts_file, "w") as f:
            json.dump(dummy_contacts, f, indent=4)
        
    try:
        with open(contacts_file, "r") as f:
            contacts = json.load(f)
        
        name_lower = name.lower()
        for contact_name, email in contacts.items():
            if name_lower in contact_name.lower():
                return f"Contact found: {contact_name} -> {email}"
                
        return f"No contact found matching '{name}'."
    except Exception as e:
        return f"Error reading contact book: {str(e)}"

workspace_tools = [read_file, search_file, create_folder, write_file]
knowledge_tools = [refresh_knowledge_base, rag_search]
productivity_tools = [send_email, calendar_today, create_event, create_task, list_tasks, upload_to_drive, search_drive, send_telegram_message, create_doc, read_doc, append_to_doc, reschedule_event, delete_event, share_drive_file, lookup_contact]

# =========================================================
# LLM INSTANCES  (one per agent, separate bindings)
# =========================================================

orchestrator_llm = ChatGroq(model=MODEL_NAME, temperature=0).with_structured_output(
    OrchestratorDecision
)
workspace_llm = ChatGroq(model=MODEL_NAME, temperature=0).bind_tools(workspace_tools)
knowledge_llm = ChatGroq(model=MODEL_NAME, temperature=0).bind_tools(knowledge_tools)
productivity_llm = ChatGroq(model=MODEL_NAME, temperature=0).bind_tools(
    productivity_tools
)

# =========================================================
# TOOL NODES  (one per agent, separate instances)
# =========================================================

workspace_tool_node = ToolNode(workspace_tools, messages_key="workspace_messages")
knowledge_tool_node = ToolNode(knowledge_tools, messages_key="knowledge_messages")
productivity_tool_node = ToolNode(
    productivity_tools, messages_key="productivity_messages"
)

# =========================================================
# ORCHESTRATOR
# =========================================================


def orchestrator(state: GraphState) -> dict:
    print("\n--- [Orchestrator] Deciding next step ---")

    # Respect Groq's 8000 TPM rate limit
    time.sleep(3)

    completed = [
        {"id": t.id, "agent": t.agent, "status": t.status, "instruction": t.instruction}
        for t in state.get("completed_tasks", [])
    ]
    artifact_summaries = [
        {"id": a.id, "title": a.title, "description": a.description}
        # some payload fix worked here
        for a in state.get("artifacts", {}).values()
    ]

    prompt = f"""You are the Orchestrator of a hierarchical multi-agent AI system.
You must assign ONE task at a time to the most appropriate agent.

User Query: {state["user_query"]}

Completed Tasks (with instructions):
{json.dumps(completed, indent=2)}

Available Artifacts:
{json.dumps(artifact_summaries, indent=2)}

Strict Rules:
1. Assign exactly ONE next task to WorkspaceAgent, KnowledgeAgent, or ProductivityAgent.
2. Look at the completed task instructions carefully. If all tasks required to fulfill the user query are completed, set finished=True NOW.
3. Do NOT repeat a task type that is already completed.
4. Only assign tasks that are directly necessary to answer the user query.
5. Do NOT set finished=True if there are pending actions requested in the user query that have not been performed yet.
6. When setting finished=True, you MUST write a final_response answering the user's query using the content/payload of the completed task artifacts.
7. When you read a file, print its content in final response which you will get in payload.
8. AGENT DEMARCATION (CRITICAL):
   - WorkspaceAgent: Use ONLY for local file system operations (read, write, search files/folders).
   - KnowledgeAgent: Use ONLY for searching the knowledge base via RAG and answering knowledge questions.
   - ProductivityAgent: Use ONLY for external APIs: Emails, Google Calendar, Tasks, Google Docs, Drive, Telegram, Contacts. If the user asks to "draft an email" or "send an email", route it HERE, never to WorkspaceAgent.
"""

    decision: OrchestratorDecision = orchestrator_llm.invoke(
        [SystemMessage(content=prompt)]
    )

    if decision.finished or decision.task is None:
        # decision.task being None means the model thinks we're done (or made an output error)
        final_msg = decision.final_response or "All tasks completed successfully."
        print("  [Orchestrator] All done. Final response ready.")
        return {"final_response": final_msg}

    new_task_counter = state["task_counter"] + 1
    new_task = Task(
        id=f"task_{new_task_counter}",
        agent=decision.task.agent,
        instruction=decision.task.instruction,
        context_artifacts=decision.task.context_artifacts,
        expected_output=decision.task.expected_output,
        status="pending",
    )
    print(f"  [Orchestrator] Assigned {new_task.id} -> {new_task.agent}")
    return {
        "current_task": new_task,
        "task_counter": new_task_counter,
        "agent_steps": 0,
        "logs": [f"Orchestrator -> {new_task.agent}: {new_task.id}"],
    }


def orchestrator_route(state: GraphState) -> str:
    if state.get("final_response"):
        return END
    task = state.get("current_task")
    if task is None:
        return END
    return task.agent


# =========================================================
# WORKSPACE AGENT
# =========================================================


def workspace_agent(state: GraphState) -> dict:
    task = state["current_task"]
    print(f"\n--- [WorkspaceAgent] Executing {task.id} ---")

    context = {
        aid: state["artifacts"][aid].payload
        for aid in task.context_artifacts
        if aid in state["artifacts"]
    }

    sys_prompt = f"""You are WorkspaceAgent. You handle file system operations.
Task: {task.instruction}
Expected Output: {task.expected_output}
Context: {json.dumps(context)}

Use the available tools to complete the task. You may call multiple tools if needed."""

    # On first call (agent_steps==0): fresh start, no prior history needed.
    # On subsequent calls: include history so LLM sees its own tool results.
    if state["agent_steps"] == 0:
        messages = [SystemMessage(content=sys_prompt)]
    else:
        messages = [SystemMessage(content=sys_prompt)] + state["workspace_messages"]

    time.sleep(2)  # respect TPM rate limit
    response = workspace_llm.invoke(messages)

    if response.tool_calls:
        print(
            f"  [WorkspaceAgent] Tool calls: {[tc['name'] for tc in response.tool_calls]}"
        )
    else:
        print("  [WorkspaceAgent] Done — no more tool calls.")

    return {"workspace_messages": [response], "agent_steps": state["agent_steps"] + 1}


def workspace_route(state: GraphState) -> str:
    # Safety guard: force finalize if too many tool loops
    if state["agent_steps"] >= MAX_AGENT_STEPS:
        print("  [WorkspaceAgent] Max steps reached, forcing finalize.")
        return "WorkspaceFinalizer"
    last_msg = state["workspace_messages"][-1]
    if hasattr(last_msg, "tool_calls") and last_msg.tool_calls:
        return "WorkspaceToolNode"
    return "WorkspaceFinalizer"


def workspace_finalizer(state: GraphState) -> dict:
    print("  [WorkspaceAgent] Finalizing task.")
    last_msg = state["workspace_messages"][-1]

    if isinstance(last_msg, ToolMessage):
        payload = last_msg.content
        tool_name = last_msg.name
    else:
        payload = last_msg.content
        tool_name = "direct_response"

    task = state["current_task"]
    new_art_counter = state["artifact_counter"] + 1
    artifact_id = f"art_{new_art_counter}"

    artifact = Artifact(
        id=artifact_id,
        type="workspace_output",
        title=f"Output of {tool_name}",
        description=f"Produced by WorkspaceAgent for {task.id}",
        payload=payload,
    )

    task.status = "completed"
    print(f"  [WorkspaceAgent] Created artifact {artifact_id}.")

    return {
        "artifacts": {artifact_id: artifact},
        "completed_tasks": [task],
        "current_task": None,
        "artifact_counter": new_art_counter,
        "agent_steps": 0,
        "logs": [f"WorkspaceAgent completed {task.id} -> {artifact_id}"],
    }


# =========================================================
# KNOWLEDGE AGENT
# =========================================================


def knowledge_agent(state: GraphState) -> dict:
    task = state["current_task"]
    print(f"\n--- [KnowledgeAgent] Executing {task.id} ---")

    context = {
        aid: state["artifacts"][aid].payload
        for aid in task.context_artifacts
        if aid in state["artifacts"]
    }

    sys_prompt = f"""You are KnowledgeAgent. You handle summarization, research, and writing tasks.
Task: {task.instruction}
Expected Output: {task.expected_output}
Context: {json.dumps(context)}

Use the available tools to complete the task. You may call multiple tools if needed."""

    if state["agent_steps"] == 0:
        messages = [SystemMessage(content=sys_prompt)]
    else:
        messages = [SystemMessage(content=sys_prompt)] + state["knowledge_messages"]

    time.sleep(2)  # respect TPM rate limit
    response = knowledge_llm.invoke(messages)

    if response.tool_calls:
        print(
            f"  [KnowledgeAgent] Tool calls: {[tc['name'] for tc in response.tool_calls]}"
        )
    else:
        print("  [KnowledgeAgent] Done — no more tool calls.")

    return {"knowledge_messages": [response], "agent_steps": state["agent_steps"] + 1}


def knowledge_route(state: GraphState) -> str:
    # Safety guard: force finalize if too many tool loops
    if state["agent_steps"] >= MAX_AGENT_STEPS:
        print("  [KnowledgeAgent] Max steps reached, forcing finalize.")
        return "KnowledgeFinalizer"
    last_msg = state["knowledge_messages"][-1]
    if hasattr(last_msg, "tool_calls") and last_msg.tool_calls:
        return "KnowledgeToolNode"
    return "KnowledgeFinalizer"


def knowledge_finalizer(state: GraphState) -> dict:
    print("  [KnowledgeAgent] Finalizing task.")
    last_msg = state["knowledge_messages"][-1]

    if isinstance(last_msg, ToolMessage):
        payload = last_msg.content
        tool_name = last_msg.name
    else:
        payload = last_msg.content
        tool_name = "direct_response"

    task = state["current_task"]
    new_art_counter = state["artifact_counter"] + 1
    artifact_id = f"art_{new_art_counter}"

    artifact = Artifact(
        id=artifact_id,
        type="knowledge_output",
        title=f"Output of {tool_name}",
        description=f"Produced by KnowledgeAgent for {task.id}",
        payload=payload,
    )

    task.status = "completed"
    print(f"  [KnowledgeAgent] Created artifact {artifact_id}.")

    return {
        "artifacts": {artifact_id: artifact},
        "completed_tasks": [task],
        "current_task": None,
        "artifact_counter": new_art_counter,
        "agent_steps": 0,
        "logs": [f"KnowledgeAgent completed {task.id} -> {artifact_id}"],
    }


# =========================================================
# PRODUCTIVITY AGENT
# =========================================================


def productivity_agent(state: GraphState) -> dict:
    task = state["current_task"]
    print(f"\n--- [ProductivityAgent] Executing {task.id} ---")

    context = {
        aid: state["artifacts"][aid].payload
        for aid in task.context_artifacts
        if aid in state["artifacts"]
    }

    sys_prompt = f"""You are ProductivityAgent. You handle emails, calendars, scheduling, Google Tasks, Telegram messages, Google Docs, looking up contacts, and Google Drive file operations.
Task: {task.instruction}
Expected Output: {task.expected_output}
Context: {json.dumps(context)}

Use the available tools to complete the task. You may call multiple tools if needed."""

    if state["agent_steps"] == 0:
        messages = [SystemMessage(content=sys_prompt)]
    else:
        messages = [SystemMessage(content=sys_prompt)] + state["productivity_messages"]

    time.sleep(2)  # respect TPM rate limit
    response = productivity_llm.invoke(messages)

    if response.tool_calls:
        print(
            f"  [ProductivityAgent] Tool calls: {[tc['name'] for tc in response.tool_calls]}"
        )
    else:
        print("  [ProductivityAgent] Done — no more tool calls.")

    return {
        "productivity_messages": [response],
        "agent_steps": state["agent_steps"] + 1,
    }


def productivity_route(state: GraphState) -> str:
    # Safety guard: force finalize if too many tool loops
    if state["agent_steps"] >= MAX_AGENT_STEPS:
        print("  [ProductivityAgent] Max steps reached, forcing finalize.")
        return "ProductivityFinalizer"
    last_msg = state["productivity_messages"][-1]
    if hasattr(last_msg, "tool_calls") and last_msg.tool_calls:
        return "ProductivityToolNode"
    return "ProductivityFinalizer"


def productivity_finalizer(state: GraphState) -> dict:
    print("  [ProductivityAgent] Finalizing task.")
    last_msg = state["productivity_messages"][-1]

    if isinstance(last_msg, ToolMessage):
        payload = last_msg.content
        tool_name = last_msg.name
    else:
        payload = last_msg.content
        tool_name = "direct_response"

    task = state["current_task"]
    new_art_counter = state["artifact_counter"] + 1
    artifact_id = f"art_{new_art_counter}"

    artifact = Artifact(
        id=artifact_id,
        type="productivity_output",
        title=f"Output of {tool_name}",
        description=f"Produced by ProductivityAgent for {task.id}",
        payload=payload,
    )

    task.status = "completed"
    print(f"  [ProductivityAgent] Created artifact {artifact_id}.")

    return {
        "artifacts": {artifact_id: artifact},
        "completed_tasks": [task],
        "current_task": None,
        "artifact_counter": new_art_counter,
        "agent_steps": 0,
        "logs": [f"ProductivityAgent completed {task.id} -> {artifact_id}"],
    }


# =========================================================
# BUILD GRAPH
# =========================================================


def build_graph():
    builder = StateGraph(GraphState)

    # ── Nodes ────────────────────────────────────────────
    builder.add_node("Orchestrator", orchestrator)

    builder.add_node("WorkspaceAgent", workspace_agent)
    builder.add_node("WorkspaceToolNode", workspace_tool_node)
    builder.add_node("WorkspaceFinalizer", workspace_finalizer)

    builder.add_node("KnowledgeAgent", knowledge_agent)
    builder.add_node("KnowledgeToolNode", knowledge_tool_node)
    builder.add_node("KnowledgeFinalizer", knowledge_finalizer)

    builder.add_node("ProductivityAgent", productivity_agent)
    builder.add_node("ProductivityToolNode", productivity_tool_node)
    builder.add_node("ProductivityFinalizer", productivity_finalizer)

    # ── Entry ─────────────────────────────────────────────
    builder.add_edge(START, "Orchestrator")

    # ── Orchestrator routes to one agent (or END) ─────────
    builder.add_conditional_edges("Orchestrator", orchestrator_route)

    # ── WorkspaceAgent mini-loop ──────────────────────────
    builder.add_conditional_edges("WorkspaceAgent", workspace_route)
    builder.add_edge("WorkspaceToolNode", "WorkspaceAgent")  # loop back for more calls
    builder.add_edge("WorkspaceFinalizer", "Orchestrator")

    # ── KnowledgeAgent mini-loop ──────────────────────────
    builder.add_conditional_edges("KnowledgeAgent", knowledge_route)
    builder.add_edge("KnowledgeToolNode", "KnowledgeAgent")  # loop back for more calls
    builder.add_edge("KnowledgeFinalizer", "Orchestrator")

    # ── ProductivityAgent mini-loop ───────────────────────
    builder.add_conditional_edges("ProductivityAgent", productivity_route)
    builder.add_edge(
        "ProductivityToolNode", "ProductivityAgent"
    )  # loop back for more calls
    builder.add_edge("ProductivityFinalizer", "Orchestrator")

    return builder.compile()


# =========================================================
# ENTRY POINT
# =========================================================

if __name__ == "__main__":
    print("=========================================================")
    print("  INITIALIZING KNOWLEDGE BASE")
    print("=========================================================")
    print(refresh_knowledge_base.invoke({}))

    graph = build_graph()

    initial_state: GraphState = {
        #         "user_query": "search the poem.txt and summarize what it contains. " ,
        "user_query": "Search for Project_plan.md in my workspace, read it, create a notes folder, write a summary to notes/summary.txt, schedule a meeting on calendar called README Review for tomorrow at 10:00 AM, and email me the summary at chaitanyashinde545@gmail.com",
        "messages": [],
        "workspace_messages": [],
        "knowledge_messages": [],
        "productivity_messages": [],
        "current_task": None,
        "completed_tasks": [],
        "artifacts": {},
        "logs": [],
        "final_response": None,
        "task_counter": 0,
        "artifact_counter": 0,
        "agent_steps": 0,
    }
 #    print(calendar_today.invoke({}))
    print("=========================================================")
    print("  MULTI-AGENT LANGGRAPH — EXPLICIT NODES & TOOL LOOPS")
    print("=========================================================")

    final_state = graph.invoke(initial_state, config={"recursion_limit": 35})

    print("\n=========================================================")
    print("  GRAPH FINISHED")
    print(f"  Final Response  : {final_state.get('final_response')}")
    print(f"  Tasks Completed : {len(final_state.get('completed_tasks', []))}")
    print(f"  Artifacts       : {len(final_state.get('artifacts', {}))}")
    print("=========================================================")

    # print(search_file.invoke({"name": "README"}))
    # print(create_folder.invoke({"path": "./demo"}))
    # print(write_file.invoke({"path": "./demo/test.txt", "text": "hello"}))
    # print(read_file.invoke({"path": "./demo/test.txt"}))

#    print(search_file.invoke({"name": "test.txt"}))
#    print( read_file.invoke({"path":"./test.txt"}))
