import operator
from typing import Annotated, Any, Dict, List, Literal, Optional, TypedDict
from pydantic import BaseModel, Field
from langchain_core.messages import AnyMessage
from langgraph.graph.message import add_messages


def merge_dicts(a: dict, b: dict) -> dict:
    c = a.copy()
    c.update(b)
    return c


class Task(BaseModel):
    id: str = Field(..., description="Unique task ID generated by Python.")
    agent: Literal["WorkspaceAgent", "KnowledgeAgent", "ProductivityAgent"]
    instruction: str
    context_artifacts: List[str] = Field(default_factory=list)
    expected_output: str
    status: str = "pending"


class Artifact(BaseModel):
    id: str
    type: str
    title: str
    description: str
    metadata: Dict[str, Any] = Field(default_factory=dict)
    payload: Any = None


class GraphState(TypedDict):
    chat_id: str
    chat_rag_enabled: bool
    uploaded_documents: list[str]
    user_query: str
    messages: Annotated[list[AnyMessage], add_messages]
    workspace_messages: Annotated[list[AnyMessage], add_messages]
    knowledge_messages: Annotated[list[AnyMessage], add_messages]
    productivity_messages: Annotated[list[AnyMessage], add_messages]
    current_task: Optional[Task]
    completed_tasks: Annotated[list[Task], operator.add]
    artifacts: Annotated[Dict[str, Artifact], merge_dicts]
    logs: Annotated[list[str], operator.add]
    final_response: Optional[str]
    task_counter: int
    artifact_counter: int
    agent_steps: int  # counts tool loops within the current agent task
